### ISSUE TITLE
KeyEscapeUtils module not found - React

### ISSUE THREAD

**Issue by ChrisCates** [toxicFork/react-three-renderer#118]
Not sure why this package is referencing this non existent component of React.

Any clues?

Here is the error logs:

```
[piping] can't execute file: /Users/chriscates/projects/Custom-Box-Builder/bin/server.js
[1] [piping] error given was: Error: Cannot find module 'react/lib/KeyEscapeUtils'
[1]     at Function.Module._resolveFilename (module.js:440:15)
[1]     at Function._module2.default._resolveFilename (/Users/chriscates/projects/Custom-Box-Builder/node_modules/require-hacker/babel-transpiled-modules/require hacker.js:423:34)
[1]     at Function.module._load (/Users/chriscates/projects/Custom-Box-Builder/node_modules/piping/lib/launcher.js:24:23)
[1]     at Module.require (module.js:468:17)
[1]     at require (internal/module.js:20:19)
[1]     at Object.<anonymous> (/Users/chriscates/projects/Custom-Box-Builder/node_modules/react-three-renderer/lib/React3Renderer.js:57:23)
[1]     at Module._compile (module.js:541:32)
[1]     at Module._extensions..js (module.js:550:10)
[1]     at require.extensions.(anonymous function) (/Users/chriscates/projects/Custom-Box-Builder/node_modules/babel-register/lib/node.js:156:7)
[1]     at Object._module2.default._extensions.(anonymous function) [as .js] (/Users/chriscates/projects/Custom-Box-Builder/node_modules/require-hacker/babel-transpiled-modules/require hacker.js:260:68)
[1] [piping] further repeats of this error will be suppressed...
[0] ./~/react-three-renderer/lib/React3Renderer.js
[0] Module not found: Error: Cannot resolve module 'react/lib/KeyEscapeUtils' in /Users/chriscates/projects/Custom-Box-Builder/node_modules/react-three-renderer/lib
[0] resolve module react/lib/KeyEscapeUtils in /Users/chriscates/projects/Custom-Box-Builder/node_modules/react-three-renderer/lib
[0]   looking for modules in /Users/chriscates/projects/Custom-Box-Builder/node_modules/react-three-renderer/src
[0]     /Users/chriscates/projects/Custom-Box-Builder/node_modules/react-three-renderer/src/react doesn't exist (module as directory)
[0]   looking for modules in /Users/chriscates/projects/Custom-Box-Builder/node_modules/react-three-renderer/node_modules
[0]     /Users/chriscates/projects/Custom-Box-Builder/node_modules/react-three-renderer/node_modules/react doesn't exist (module as directory)
[0]   looking for modules in /Users/chriscates/projects/Custom-Box-Builder/src
[0]     /Users/chriscates/projects/Custom-Box-Builder/src/react doesn't exist (module as directory)
[0]   looking for modules in /Users/chriscates/node_modules
[0]     /Users/chriscates/node_modules/react doesn't exist (module as directory)
[0]   looking for modules in /Users/chriscates/projects/Custom-Box-Builder/node_modules
[0]     resolve 'file' or 'directory' lib/KeyEscapeUtils in /Users/chriscates/projects/Custom-Box-Builder/node_modules/react
[0]       resolve file
[0]         /Users/chriscates/projects/Custom-Box-Builder/node_modules/react/lib/KeyEscapeUtils doesn't exist
[0]         /Users/chriscates/projects/Custom-Box-Builder/node_modules/react/lib/KeyEscapeUtils.json doesn't exist
[0]         /Users/chriscates/projects/Custom-Box-Builder/node_modules/react/lib/KeyEscapeUtils.js doesn't exist
[0]         /Users/chriscates/projects/Custom-Box-Builder/node_modules/react/lib/KeyEscapeUtils.jsx doesn't exist
[0]       resolve directory
[0]         /Users/chriscates/projects/Custom-Box-Builder/node_modules/react/lib/KeyEscapeUtils doesn't exist (directory default file)
[0]         /Users/chriscates/projects/Custom-Box-Builder/node_modules/react/lib/KeyEscapeUtils/package.json doesn't exist (directory description file)
[0] [/Users/chriscates/projects/Custom-Box-Builder/node_modules/react-three-renderer/src/react]
[0] [/Users/chriscates/projects/Custom-Box-Builder/node_modules/react-three-renderer/node_modules/react]
[0] [/Users/chriscates/projects/Custom-Box-Builder/src/react]
[0] [/Users/chriscates/node_modules/react]
[0] [/Users/chriscates/projects/Custom-Box-Builder/node_modules/react/lib/KeyEscapeUtils]
[0] [/Users/chriscates/projects/Custom-Box-Builder/node_modules/react/lib/KeyEscapeUtils.json]
[0] [/Users/chriscates/projects/Custom-Box-Builder/node_modules/react/lib/KeyEscapeUtils.js]
[0] [/Users/chriscates/projects/Custom-Box-Builder/node_modules/react/lib/KeyEscapeUtils.jsx]
[0]  @ ./~/react-three-renderer/lib/React3Renderer.js 57:22-57
[0] ./~/react-three-renderer/lib/React3Renderer.js
[0] Module not found: Error: Cannot resolve module 'react/lib/getHostComponentFromComposite' in /Users/chriscates/projects/Custom-Box-Builder/node_modules/react-three-renderer/lib
[0] resolve module react/lib/getHostComponentFromComposite in /Users/chriscates/projects/Custom-Box-Builder/node_modules/react-three-renderer/lib
[0]   looking for modules in /Users/chriscates/projects/Custom-Box-Builder/node_modules/react-three-renderer/src
[0]     /Users/chriscates/projects/Custom-Box-Builder/node_modules/react-three-renderer/src/react doesn't exist (module as directory)
[0]   looking for modules in /Users/chriscates/projects/Custom-Box-Builder/node_modules/react-three-renderer/node_modules
[0]     /Users/chriscates/projects/Custom-Box-Builder/node_modules/react-three-renderer/node_modules/react doesn't exist (module as directory)
[0]   looking for modules in /Users/chriscates/projects/Custom-Box-Builder/src
[0]     /Users/chriscates/projects/Custom-Box-Builder/src/react doesn't exist (module as directory)
[0]   looking for modules in /Users/chriscates/node_modules
[0]     /Users/chriscates/node_modules/react doesn't exist (module as directory)
[0]   looking for modules in /Users/chriscates/projects/Custom-Box-Builder/node_modules
[0]     resolve 'file' or 'directory' lib/getHostComponentFromComposite in /Users/chriscates/projects/Custom-Box-Builder/node_modules/react
[0]       resolve file
[0]         /Users/chriscates/projects/Custom-Box-Builder/node_modules/react/lib/getHostComponentFromComposite doesn't exist
[0]         /Users/chriscates/projects/Custom-Box-Builder/node_modules/react/lib/getHostComponentFromComposite.json doesn't exist
[0]         /Users/chriscates/projects/Custom-Box-Builder/node_modules/react/lib/getHostComponentFromComposite.js doesn't exist
[0]         /Users/chriscates/projects/Custom-Box-Builder/node_modules/react/lib/getHostComponentFromComposite.jsx doesn't exist
[0]       resolve directory
[0]         /Users/chriscates/projects/Custom-Box-Builder/node_modules/react/lib/getHostComponentFromComposite doesn't exist (directory default file)
[0]         /Users/chriscates/projects/Custom-Box-Builder/node_modules/react/lib/getHostComponentFromComposite/package.json doesn't exist (directory description file)
[0] [/Users/chriscates/projects/Custom-Box-Builder/node_modules/react-three-renderer/src/react]
[0] [/Users/chriscates/projects/Custom-Box-Builder/node_modules/react-three-renderer/node_modules/react]
[0] [/Users/chriscates/projects/Custom-Box-Builder/src/react]
[0] [/Users/chriscates/node_modules/react]
[0] [/Users/chriscates/projects/Custom-Box-Builder/node_modules/react/lib/getHostComponentFromComposite]
[0] [/Users/chriscates/projects/Custom-Box-Builder/node_modules/react/lib/getHostComponentFromComposite.json]
[0] [/Users/chriscates/projects/Custom-Box-Builder/node_modules/react/lib/getHostComponentFromComposite.js]
[0] [/Users/chriscates/projects/Custom-Box-Builder/node_modules/react/lib/getHostComponentFromComposite.jsx]
[0]  @ ./~/react-three-renderer/lib/React3Renderer.js 65:37-87
[0] ./~/react-three-renderer/lib/React3Renderer.js
[0] Module not found: Error: Cannot resolve module 'react/lib/ReactInstrumentation' in /Users/chriscates/projects/Custom-Box-Builder/node_modules/react-three-renderer/lib
[0] resolve module react/lib/ReactInstrumentation in /Users/chriscates/projects/Custom-Box-Builder/node_modules/react-three-renderer/lib
[0]   looking for modules in /Users/chriscates/projects/Custom-Box-Builder/node_modules/react-three-renderer/src
[0]     /Users/chriscates/projects/Custom-Box-Builder/node_modules/react-three-renderer/src/react doesn't exist (module as directory)
[0]   looking for modules in /Users/chriscates/projects/Custom-Box-Builder/node_modules/react-three-renderer/node_modules
[0]     /Users/chriscates/projects/Custom-Box-Builder/node_modules/react-three-renderer/node_modules/react doesn't exist (module as directory)
[0]   looking for modules in /Users/chriscates/projects/Custom-Box-Builder/src
[0]     /Users/chriscates/projects/Custom-Box-Builder/src/react doesn't exist (module as directory)
[0]   looking for modules in /Users/chriscates/node_modules
[0]     /Users/chriscates/node_modules/react doesn't exist (module as directory)
[0]   looking for modules in /Users/chriscates/projects/Custom-Box-Builder/node_modules
[0]     resolve 'file' or 'directory' lib/ReactInstrumentation in /Users/chriscates/projects/Custom-Box-Builder/node_modules/react
[0]       resolve file
[0]         /Users/chriscates/projects/Custom-Box-Builder/node_modules/react/lib/ReactInstrumentation doesn't exist
[0]         /Users/chriscates/projects/Custom-Box-Builder/node_modules/react/lib/ReactInstrumentation.json doesn't exist
[0]         /Users/chriscates/projects/Custom-Box-Builder/node_modules/react/lib/ReactInstrumentation.js doesn't exist
[0]         /Users/chriscates/projects/Custom-Box-Builder/node_modules/react/lib/ReactInstrumentation.jsx doesn't exist
[0]       resolve directory
[0]         /Users/chriscates/projects/Custom-Box-Builder/node_modules/react/lib/ReactInstrumentation doesn't exist (directory default file)
[0]         /Users/chriscates/projects/Custom-Box-Builder/node_modules/react/lib/ReactInstrumentation/package.json doesn't exist (directory description file)
[0] [/Users/chriscates/projects/Custom-Box-Builder/node_modules/react-three-renderer/src/react]
[0] [/Users/chriscates/projects/Custom-Box-Builder/node_modules/react-three-renderer/node_modules/react]
[0] [/Users/chriscates/projects/Custom-Box-Builder/src/react]
[0] [/Users/chriscates/node_modules/react]
[0] [/Users/chriscates/projects/Custom-Box-Builder/node_modules/react/lib/ReactInstrumentation]
[0] [/Users/chriscates/projects/Custom-Box-Builder/node_modules/react/lib/ReactInstrumentation.json]
[0] [/Users/chriscates/projects/Custom-Box-Builder/node_modules/react/lib/ReactInstrumentation.js]
[0] [/Users/chriscates/projects/Custom-Box-Builder/node_modules/react/lib/ReactInstrumentation.jsx]
[0]  @ ./~/react-three-renderer/lib/React3Renderer.js 73:28-69
[0] ./~/react-three-renderer/lib/React3Renderer.js
[0] Module not found: Error: Cannot resolve module 'react/lib/ReactComponentTreeHook' in /Users/chriscates/projects/Custom-Box-Builder/node_modules/react-three-renderer/lib
[0] resolve module react/lib/ReactComponentTreeHook in /Users/chriscates/projects/Custom-Box-Builder/node_modules/react-three-renderer/lib
[0]   looking for modules in /Users/chriscates/projects/Custom-Box-Builder/node_modules/react-three-renderer/src
[0]     /Users/chriscates/projects/Custom-Box-Builder/node_modules/react-three-renderer/src/react doesn't exist (module as directory)
[0]   looking for modules in /Users/chriscates/projects/Custom-Box-Builder/node_modules/react-three-renderer/node_modules
[0]     /Users/chriscates/projects/Custom-Box-Builder/node_modules/react-three-renderer/node_modules/react doesn't exist (module as directory)
[0]   looking for modules in /Users/chriscates/projects/Custom-Box-Builder/src
[0]     /Users/chriscates/projects/Custom-Box-Builder/src/react doesn't exist (module as directory)
[0]   looking for modules in /Users/chriscates/node_modules
[0]     /Users/chriscates/node_modules/react doesn't exist (module as directory)
[0]   looking for modules in /Users/chriscates/projects/Custom-Box-Builder/node_modules
[0]     resolve 'file' or 'directory' lib/ReactComponentTreeHook in /Users/chriscates/projects/Custom-Box-Builder/node_modules/react
[0]       resolve file
[0]         /Users/chriscates/projects/Custom-Box-Builder/node_modules/react/lib/ReactComponentTreeHook doesn't exist
[0]         /Users/chriscates/projects/Custom-Box-Builder/node_modules/react/lib/ReactComponentTreeHook.json doesn't exist
[0]         /Users/chriscates/projects/Custom-Box-Builder/node_modules/react/lib/ReactComponentTreeHook.js doesn't exist
[0]         /Users/chriscates/projects/Custom-Box-Builder/node_modules/react/lib/ReactComponentTreeHook.jsx doesn't exist
[0]       resolve directory
[0]         /Users/chriscates/projects/Custom-Box-Builder/node_modules/react/lib/ReactComponentTreeHook doesn't exist (directory default file)
[0]         /Users/chriscates/projects/Custom-Box-Builder/node_modules/react/lib/ReactComponentTreeHook/package.json doesn't exist (directory description file)
[0] [/Users/chriscates/projects/Custom-Box-Builder/node_modules/react-three-renderer/src/react]
[0] [/Users/chriscates/projects/Custom-Box-Builder/node
[0] webpack built eedbef93951c176177d2 in 45681ms
[0] _modules/react-three-renderer/node_modules/react]
[0] [/Users/chriscates/projects/Custom-Box-Builder/src/react]
[0] [/Users/chriscates/node_modules/react]
[0] [/Users/chriscates/projects/Custom-Box-Builder/node_modules/react/lib/ReactComponentTreeHook]
[0] [/Users/chriscates/projects/Custom-Box-Builder/node_modules/react/lib/ReactComponentTreeHook.json]
[0] [/Users/chriscates/projects/Custom-Box-Builder/node_modules/react/lib/ReactComponentTreeHook.js]
[0] [/Users/chriscates/projects/Custom-Box-Builder/node_modules/react/lib/ReactComponentTreeHook.jsx]
[0]  @ ./~/react-three-renderer/lib/React3Renderer.js 137:29-72
[0] ./~/react-three-renderer/lib/InternalComponent.js
[0] Module not found: Error: Cannot resolve module 'react/lib/ReactInstrumentation' in /Users/chriscates/projects/Custom-Box-Builder/node_modules/react-three-renderer/lib
[0] resolve module react/lib/ReactInstrumentation in /Users/chriscates/projects/Custom-Box-Builder/node_modules/react-three-renderer/lib
[0]   looking for modules in /Users/chriscates/projects/Custom-Box-Builder/node_modules/react-three-renderer/src
[0]     /Users/chriscates/projects/Custom-Box-Builder/node_modules/react-three-renderer/src/react doesn't exist (module as directory)
[0]   looking for modules in /Users/chriscates/projects/Custom-Box-Builder/node_modules/react-three-renderer/node_modules
[0]     /Users/chriscates/projects/Custom-Box-Builder/node_modules/react-three-renderer/node_modules/react doesn't exist (module as directory)
[0]   looking for modules in /Users/chriscates/projects/Custom-Box-Builder/src
[0]     /Users/chriscates/projects/Custom-Box-Builder/src/react doesn't exist (module as directory)
[0]   looking for modules in /Users/chriscates/projects/Custom-Box-Builder/node_modules
[0]     resolve 'file' or 'directory' lib/ReactInstrumentation in /Users/chriscates/projects/Custom-Box-Builder/node_modules/react
[0]       resolve file
[0]         /Users/chriscates/projects/Custom-Box-Builder/node_modules/react/lib/ReactInstrumentation doesn't exist
[0]         /Users/chriscates/projects/Custom-Box-Builder/node_modules/react/lib/ReactInstrumentation.json doesn't exist
[0]         /Users/chriscates/projects/Custom-Box-Builder/node_modules/react/lib/ReactInstrumentation.js doesn't exist
[0]         /Users/chriscates/projects/Custom-Box-Builder/node_modules/react/lib/ReactInstrumentation.jsx doesn't exist
[0]       resolve directory
[0]         /Users/chriscates/projects/Custom-Box-Builder/node_modules/react/lib/ReactInstrumentation/package.json doesn't exist (directory description file)
[0]         /Users/chriscates/projects/Custom-Box-Builder/node_modules/react/lib/ReactInstrumentation doesn't exist (directory default file)
[0]   looking for modules in /Users/chriscates/node_modules
[0]     /Users/chriscates/node_modules/react doesn't exist (module as directory)
[0] [/Users/chriscates/projects/Custom-Box-Builder/node_modules/react-three-renderer/src/react]
[0] [/Users/chriscates/projects/Custom-Box-Builder/node_modules/react-three-renderer/node_modules/react]
[0] [/Users/chriscates/projects/Custom-Box-Builder/src/react]
[0] [/Users/chriscates/projects/Custom-Box-Builder/node_modules/react/lib/ReactInstrumentation]
[0] [/Users/chriscates/projects/Custom-Box-Builder/node_modules/react/lib/ReactInstrumentation.json]
[0] [/Users/chriscates/projects/Custom-Box-Builder/node_modules/react/lib/ReactInstrumentation.js]
[0] [/Users/chriscates/projects/Custom-Box-Builder/node_modules/react/lib/ReactInstrumentation.jsx]
[0] [/Users/chriscates/node_modules/react]
[0]  @ ./~/react-three-renderer/lib/InternalComponent.js 31:28-69
[0] ./~/react-three-renderer/lib/React3CompositeComponentWrapper.js
[0] Module not found: Error: Cannot resolve module 'react/lib/ReactInstrumentation' in /Users/chriscates/projects/Custom-Box-Builder/node_modules/react-three-renderer/lib
[0] resolve module react/lib/ReactInstrumentation in /Users/chriscates/projects/Custom-Box-Builder/node_modules/react-three-renderer/lib
[0]   looking for modules in /Users/chriscates/projects/Custom-Box-Builder/node_modules/react-three-renderer/src
[0]     /Users/chriscates/projects/Custom-Box-Builder/node_modules/react-three-renderer/src/react doesn't exist (module as directory)
[0]   looking for modules in /Users/chriscates/projects/Custom-Box-Builder/node_modules/react-three-renderer/node_modules
[0]     /Users/chriscates/projects/Custom-Box-Builder/node_modules/react-three-renderer/node_modules/react doesn't exist (module as directory)
[0]   looking for modules in /Users/chriscates/projects/Custom-Box-Builder/src
[0]     /Users/chriscates/projects/Custom-Box-Builder/src/react doesn't exist (module as directory)
[0]   looking for modules in /Users/chriscates/projects/Custom-Box-Builder/node_modules
[0]     resolve 'file' or 'directory' lib/ReactInstrumentation in /Users/chriscates/projects/Custom-Box-Builder/node_modules/react
[0]       resolve file
[0]         /Users/chriscates/projects/Custom-Box-Builder/node_modules/react/lib/ReactInstrumentation doesn't exist
[0]         /Users/chriscates/projects/Custom-Box-Builder/node_modules/react/lib/ReactInstrumentation.json doesn't exist
[0]         /Users/chriscates/projects/Custom-Box-Builder/node_modules/react/lib/ReactInstrumentation.js doesn't exist
[0]         /Users/chriscates/projects/Custom-Box-Builder/node_modules/react/lib/ReactInstrumentation.jsx doesn't exist
[0]       resolve directory
[0]         /Users/chriscates/projects/Custom-Box-Builder/node_modules/react/lib/ReactInstrumentation/package.json doesn't exist (directory description file)
[0]         /Users/chriscates/projects/Custom-Box-Builder/node_modules/react/lib/ReactInstrumentation doesn't exist (directory default file)
[0]   looking for modules in /Users/chriscates/node_modules
[0]     /Users/chriscates/node_modules/react doesn't exist (module as directory)
[0] [/Users/chriscates/projects/Custom-Box-Builder/node_modules/react-three-renderer/src/react]
[0] [/Users/chriscates/projects/Custom-Box-Builder/node_modules/react-three-renderer/node_modules/react]
[0] [/Users/chriscates/projects/Custom-Box-Builder/src/react]
[0] [/Users/chriscates/projects/Custom-Box-Builder/node_modules/react/lib/ReactInstrumentation]
[0] [/Users/chriscates/projects/Custom-Box-Builder/node_modules/react/lib/ReactInstrumentation.json]
[0] [/Users/chriscates/projects/Custom-Box-Builder/node_modules/react/lib/ReactInstrumentation.js]
[0] [/Users/chriscates/projects/Custom-Box-Builder/node_modules/react/lib/ReactInstrumentation.jsx]
[0] [/Users/chriscates/node_modules/react]
[0]  @ ./~/react-three-renderer/lib/React3CompositeComponentWrapper.js 31:28-69
[0] ./~/react-three-renderer/lib/utils/removeDevTool.js
[0] Module not found: Error: Cannot resolve module 'react/lib/ReactInstrumentation' in /Users/chriscates/projects/Custom-Box-Builder/node_modules/react-three-renderer/lib/utils
[0] resolve module react/lib/ReactInstrumentation in /Users/chriscates/projects/Custom-Box-Builder/node_modules/react-three-renderer/lib/utils
[0]   looking for modules in /Users/chriscates/projects/Custom-Box-Builder/node_modules/react-three-renderer/src
[0]     /Users/chriscates/projects/Custom-Box-Builder/node_modules/react-three-renderer/src/react doesn't exist (module as directory)
[0]   looking for modules in /Users/chriscates/projects/Custom-Box-Builder/node_modules/react-three-renderer/node_modules
[0]     /Users/chriscates/projects/Custom-Box-Builder/node_modules/react-three-renderer/node_modules/react doesn't exist (module as directory)
[0]   looking for modules in /Users/chriscates/projects/Custom-Box-Builder/src
[0]     /Users/chriscates/projects/Custom-Box-Builder/src/react doesn't exist (module as directory)
[0]   looking for modules in /Users/chriscates/projects/Custom-Box-Builder/node_modules
[0]     resolve 'file' or 'directory' lib/ReactInstrumentation in /Users/chriscates/projects/Custom-Box-Builder/node_modules/react
[0]       resolve file
[0]         /Users/chriscates/projects/Custom-Box-Builder/node_modules/react/lib/ReactInstrumentation doesn't exist
[0]         /Users/chriscates/projects/Custom-Box-Builder/node_modules/react/lib/ReactInstrumentation.json doesn't exist
[0]         /Users/chriscates/projects/Custom-Box-Builder/node_modules/react/lib/ReactInstrumentation.js doesn't exist
[0]         /Users/chriscates/projects/Custom-Box-Builder/node_modules/react/lib/ReactInstrumentation.jsx doesn't exist
[0]       resolve directory
[0]         /Users/chriscates/projects/Custom-Box-Builder/node_modules/react/lib/ReactInstrumentation/package.json doesn't exist (directory description file)
[0]         /Users/chriscates/projects/Custom-Box-Builder/node_modules/react/lib/ReactInstrumentation doesn't exist (directory default file)
[0]   looking for modules in /Users/chriscates/node_modules
[0]     /Users/chriscates/node_modules/react doesn't exist (module as directory)
[0] [/Users/chriscates/projects/Custom-Box-Builder/node_modules/react-three-renderer/src/react]
[0] [/Users/chriscates/projects/Custom-Box-Builder/node_modules/react-three-renderer/node_modules/react]
[0] [/Users/chriscates/projects/Custom-Box-Builder/src/react]
[0] [/Users/chriscates/projects/Custom-Box-Builder/node_modules/react/lib/ReactInstrumentation]
[0] [/Users/chriscates/projects/Custom-Box-Builder/node_modules/react/lib/ReactInstrumentation.json]
[0] [/Users/chriscates/projects/Custom-Box-Builder/node_modules/react/lib/ReactInstrumentation.js]
[0] [/Users/chriscates/projects/Custom-Box-Builder/node_modules/react/lib/ReactInstrumentation.jsx]
[0] [/Users/chriscates/node_modules/react]
[0]  @ ./~/react-three-renderer/lib/utils/removeDevTool.js 3:28-69
[0] ./~/react-three-renderer/lib/utils/removeDevTool.js
[0] Module not found: Error: Cannot resolve module 'react/lib/ReactDOMUnknownPropertyHook' in /Users/chriscates/projects/Custom-Box-Builder/node_modules/react-three-renderer/lib/utils
[0] resolve module react/lib/ReactDOMUnknownPropertyHook in /Users/chriscates/projects/Custom-Box-Builder/node_modules/react-three-renderer/lib/utils
[0]   looking for modules in /Users/chriscates/projects/Custom-Box-Builder/node_modules/react-three-renderer/src
[0]     /Users/chriscates/projects/Custom-Box-Builder/node_modules/react-three-renderer/src/react doesn't exist (module as directory)
[0]   looking for modules in /Users/chriscates/projects/Custom-Box-Builder/node_modules/react-three-renderer/node_modules
[0]     /Users/chriscates/projects/Custom-Box-Builder/node_modules/react-three-renderer/node_modules/react doesn't exist (module as directory)
[0]   looking for modules in /Users/chriscates/projects/Custom-Box-Builder/src
[0]     /Users/chriscates/projects/Custom-Box-Builder/src/react doesn't exist (module as directory)
[0]   looking for modules in /Users/chriscates/node_modules
[0]     /Users/chriscates/node_modules/react doesn't exist (module as directory)
[0]   looking for modules in /Users/chriscates/projects/Custom-Box-Builder/node_modules
[0]     resolve 'file' or 'directory' lib/ReactDOMUnknownPropertyHook in /Users/chriscates/projects/Custom-Box-Builder/node_modules/react
[0]       resolve file
[0]         /Users/chriscates/projects/Custom-Box-Builder/node_modules/react/lib/ReactDOMUnknownPropertyHook doesn't exist
[0]         /Users/chriscates/projects/Custom-Box-Builder/node_modules/react/lib/ReactDOMUnknownPropertyHook.json doesn't exist
[0]         /Users/chriscates/projects/Custom-Box-Builder/node_modules/react/lib/ReactDOMUnknownPropertyHook.js doesn't exist
[0]         /Users/chriscates/projects/Custom-Box-Builder/node_modules/react/lib/ReactDOMUnknownPropertyHook.jsx doesn't exist
[0]       resolve directory
[0]         /Users/chriscates/projects/Custom-Box-Builder/node_modules/react/lib/ReactDOMUnknownPropertyHook doesn't exist (directory default file)
[0]         /Users/chriscates/projects/Custom-Box-Builder/node_modules/react/lib/ReactDOMUnknownPropertyHook/package.json doesn't exist (directory description file)
[0] [/Users/chriscates/projects/Custom-Box-Builder/node_modules/react-three-renderer/src/react]
[0] [/Users/chriscates/projects/Custom-Box-Builder/node
[0] _modules/react-three-renderer/node_modules/react]
[0] [/Users/chriscates/projects/Custom-Box-Builder/src/react]
[0] [/Users/chriscates/node_modules/react]
[0] [/Users/chriscates/projects/Custom-Box-Builder/node_modules/react/lib/ReactDOMUnknownPropertyHook]
[0] [/Users/chriscates/projects/Custom-Box-Builder/node_modules/react/lib/ReactDOMUnknownPropertyHook.json]
[0] [/Users/chriscates/projects/Custom-Box-Builder/node_modules/react/lib/ReactDOMUnknownPropertyHook.js]
[0] [/Users/chriscates/projects/Custom-Box-Builder/node_modules/react/lib/ReactDOMUnknownPropertyHook.jsx]
[0]  @ ./~/react-three-renderer/lib/utils/removeDevTool.js 7:35-83
[0] ./~/react-three-renderer/lib/utils/removeDevTool.js
[0] Module not found: Error: Cannot resolve module 'react/lib/ReactDOMNullInputValuePropHook' in /Users/chriscates/projects/Custom-Box-Builder/node_modules/react-three-renderer/lib/utils
[0] resolve module react/lib/ReactDOMNullInputValuePropHook in /Users/chriscates/projects/Custom-Box-Builder/node_modules/react-three-renderer/lib/utils
[0]   looking for modules in /Users/chriscates/projects/Custom-Box-Builder/node_modules/react-three-renderer/src
[0]     /Users/chriscates/projects/Custom-Box-Builder/node_modules/react-three-renderer/src/react doesn't exist (module as directory)
[0]   looking for modules in /Users/chriscates/projects/Custom-Box-Builder/node_modules/react-three-renderer/node_modules
[0]     /Users/chriscates/projects/Custom-Box-Builder/node_modules/react-three-renderer/node_modules/react doesn't exist (module as directory)
[0]   looking for modules in /Users/chriscates/projects/Custom-Box-Builder/src
[0]     /Users/chriscates/projects/Custom-Box-Builder/src/react doesn't exist (module as directory)
[0]   looking for modules in /Users/chriscates/node_modules
[0]     /Users/chriscates/node_modules/react doesn't exist (module as directory)
[0]   looking for modules in /Users/chriscates/projects/Custom-Box-Builder/node_modules
[0]     resolve 'file' or 'directory' lib/ReactDOMNullInputValuePropHook in /Users/chriscates/projects/Custom-Box-Builder/node_modules/react
[0]       resolve file
[0]         /Users/chriscates/projects/Custom-Box-Builder/node_modules/react/lib/ReactDOMNullInputValuePropHook doesn't exist
[0]         /Users/chriscates/projects/Custom-Box-Builder/node_modules/react/lib/ReactDOMNullInputValuePropHook.json doesn't exist
[0]         /Users/chriscates/projects/Custom-Box-Builder/node_modules/react/lib/ReactDOMNullInputValuePropHook.js doesn't exist
[0]         /Users/chriscates/projects/Custom-Box-Builder/node_modules/react/lib/ReactDOMNullInputValuePropHook.jsx doesn't exist
[0]       resolve directory
[0]         /Users/chriscates/projects/Custom-Box-Builder/node_modules/react/lib/ReactDOMNullInputValuePropHook doesn't exist (directory default file)
[0]         /Users/chriscates/projects/Custom-Box-Builder/node_modules/react/lib/ReactDOMNullInputValuePropHook/package.json doesn't exist (directory description file)
[0] [/Users/chriscates/projects/Custom-Box-Builder/node_modules/react-three-renderer/src/react]
[0] [/Users/chriscates/projects/Custom-Box-Builder/node_modules/react-three-renderer/node_modules/react]
[0] [/Users/chriscates/projects/Custom-Box-Builder/src/react]
[0] [/Users/chriscates/node_modules/react]
[0] [/Users/chriscates/projects/Custom-Box-Builder/node_modules/react/lib/ReactDOMNullInputValuePropHook]
[0] [/Users/chriscates/projects/Custom-Box-Builder/node_modules/react/lib/ReactDOMNullInputValuePropHook.json]
[0] [/Users/chriscates/projects/Custom-Box-Builder/node_modules/react/lib/ReactDOMNullInputValuePropHook.js]
[0] [/Users/chriscates/projects/Custom-Box-Builder/node_modules/react/lib/ReactDOMNullInputValuePropHook.jsx]
[0]  @ ./~/react-three-renderer/lib/utils/removeDevTool.js 11:38-89
[0] ./~/react-three-renderer/lib/descriptors/THREEElementDescriptor.js
[0] Module not found: Error: Cannot resolve module 'react/lib/checkReactTypeSpec' in /Users/chriscates/projects/Custom-Box-Builder/node_modules/react-three-renderer/lib/descriptors
[0] resolve module react/lib/checkReactTypeSpec in /Users/chriscates/projects/Custom-Box-Builder/node_modules/react-three-renderer/lib/descriptors
[0]   looking for modules in /Users/chriscates/projects/Custom-Box-Builder/node_modules/react-three-renderer/src
[0]     /Users/chriscates/projects/Custom-Box-Builder/node_modules/react-three-renderer/src/react doesn't exist (module as directory)
[0]   looking for modules in /Users/chriscates/projects/Custom-Box-Builder/node_modules/react-three-renderer/node_modules
[0]     /Users/chriscates/projects/Custom-Box-Builder/node_modules/react-three-renderer/node_modules/react doesn't exist (module as directory)
[0]   looking for modules in /Users/chriscates/projects/Custom-Box-Builder/src
[0]     /Users/chriscates/projects/Custom-Box-Builder/src/react doesn't exist (module as directory)
[0]   looking for modules in /Users/chriscates/node_modules
[0]     /Users/chriscates/node_modules/react doesn't exist (module as directory)
[0]   looking for modules in /Users/chriscates/projects/Custom-Box-Builder/node_modules
[0]     resolve 'file' or 'directory' lib/checkReactTypeSpec in /Users/chriscates/projects/Custom-Box-Builder/node_modules/react
[0]       resolve file
[0]         /Users/chriscates/projects/Custom-Box-Builder/node_modules/react/lib/checkReactTypeSpec doesn't exist
[0]         /Users/chriscates/projects/Custom-Box-Builder/node_modules/react/lib/checkReactTypeSpec.json doesn't exist
[0]         /Users/chriscates/projects/Custom-Box-Builder/node_modules/react/lib/checkReactTypeSpec.js doesn't exist
[0]         /Users/chriscates/projects/Custom-Box-Builder/node_modules/react/lib/checkReactTypeSpec.jsx doesn't exist
[0]       resolve directory
[0]         /Users/chriscates/projects/Custom-Box-Builder/node_modules/react/lib/checkReactTypeSpec doesn't exist (directory default file)
[0]         /Users/chriscates/projects/Custom-Box-Builder/node_modules/react/lib/checkReactTypeSpec/package.json doesn't exist (directory description file)
[0] [/Users/chriscates/projects/Custom-Box-Builder/node_modules/react-three-renderer/src/react]
[0] [/Users/chriscates/projects/Custom-Box-Builder/node_modules/react-three-renderer/node_modules/react]
[0] [/Users/chriscates/projects/Custom-Box-Builder/src/react]
[0] [/Users/chriscates/node_modules/react]
[0] [/Users/chriscates/projects/Custom-Box-Builder/node_modules/react/lib/checkReactTypeSpec]
[0] [/Users/chriscates/projects/Custom-Box-Builder/node_modules/react/lib/checkReactTypeSpec.json]
[0] [/Users/chriscates/projects/Custom-Box-Builder/node_modules/react/lib/checkReactTypeSpec.js]
[0] [/Users/chriscates/projects/Custom-Box-Builder/node_modules/react/lib/checkReactTypeSpec.jsx]
[0]  @ ./~/react-three-renderer/lib/descriptors/THREEElementDescriptor.js 27:26-65
```

**Comment by toxicFork** [comment]
Which version of React are you on? This package only supports `15.3.1` at the moment.
